wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709220158.966591
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
